/*
 * Copyright (C) 2015 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* This file is used to define the properties of the filesystem
** images generated by build tools (mkbootfs and mkyaffs2image) and
** by the device side of adb.
*/

static const struct fs_path_config android_device_dirs[] = {
    { 00777, AID_SYSTEM, AID_SYSTEM, 0, "data/anr" },
    { 00771, AID_MOT_TCMD,  AID_SHELL, 0, "data/local/12m/batch" },
    { 00771, AID_MOT_TCMD,  AID_SHELL, 0, "data/local/12m" },
    { 00771, AID_MOT_TCMD,  AID_SHELL, 0, "data/local/tmp" },
    { 00775, AID_SYSTEM, AID_SYSTEM, 0, "data/tombstones" },
    { 00777, AID_SYSTEM, AID_SYSTEM, 0, "data/touchpad" },
    { 00770, AID_RADIO,  AID_LOG,    0, "data/logger" },
    { 00755, AID_ROOT,   AID_ROOT,   0, "system/usr/bin" },
    { 00775, AID_ROOT,   AID_ROOT,   0, "system/etc/touchpad" },
};

static const struct fs_path_config android_device_files[] = {
    { 00440, AID_BLUETOOTH, AID_BLUETOOTH, 0, "system/etc/dbus.conf" },
    { 00755, AID_ROOT,      AID_SHELL,     0, "system/etc/12m_files_copy.sh" },
    { 00544, AID_ROOT,      AID_SHELL,     0, "system/etc/install-recovery.sh" },
    { 00660, AID_RADIO,     AID_RADIO,     0, "data/logger/bplogd.clog" },
    { 00660, AID_RADIO,     AID_RADIO,     0, "data/logger/bplogd.conf" },
    { 04770, AID_ROOT,      AID_RADIO,     0, "system/bin/pppd-moto_ril" },
    { 00750, AID_ROOT,      AID_RADIO,     0, "system/bin/mfa" }, /* STE */
    { 00555, AID_ROOT,      AID_SHELL,     0, "system/bin/fwupgrade" },
    { 00555, AID_ROOT,      AID_ROOT,      0, "system/usr/bin/brcm_guci_drv" },
    { 00750, AID_ROOT,      AID_SHELL,     0, "charger*" },
};
