#include "../../../../../hardware/libhardware/include/hardware/camera_common.h"

#undef CAMERA_MODULE_API_VERSION_CURRENT
#define CAMERA_MODULE_API_VERSION_CURRENT CAMERA_MODULE_API_VERSION_2_0

#undef CAMERA_DEVICE_API_VERSION_CURRENT
#define CAMERA_DEVICE_API_VERSION_CURRENT CAMERA_DEVICE_API_VERSION_1_0
